import numpy as np
import matplotlib.pyplot as plt
#matplotlib inline

# Make sure that caffe is on the python path:
caffe_root = './'  # this file is expected to be in {caffe_root}/examples
import sys
sys.path.insert(0, caffe_root + 'python')

import caffe

plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

import os

#caffe.set_mode_cpu()
net = caffe.Net('examples/mnist/lenet_train_test_topology.prototxt',
                'examples/mnist/lenet_topology_iter_10000.caffemodel',
                caffe.TEST)
# net = caffe.Net('Homework2/Models/Definitions/Autogenerated/autoencoder_test.prototxt',
#                 'Homework2/Models/Binaries/autoencoder_iter_5000.caffemodel',
#                 caffe.TEST)

# input preprocessing: 'data' is the name of the input blob == net.inputs[0]
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1))

# set net to batch size of 50
net.blobs['data'].reshape(1, 1, 28, 28)
net.blobs['data'].data[...] = transformer.preprocess('data', caffe.io.load_image(caffe_root + 'examples/images/mnist_1.png',color=False))

#TODO: figure out the deprocess error thing

# CPU mode
net.forward()  # call once for allocation
plt.imshow(np.squeeze(net.blobs['data'].data[0]))
plt.savefig('visualize/viz_results/mnist_lenet_topology/input.png')

# check the output data dimension for all layers
[(k, v.data.shape) for k, v in net.blobs.items()]

#check the parameter dimensions for each layer -- weight/filter
[(k, v[0].data.shape) for k, v in net.params.items()]

# take an array of shape (n, height, width) or (n, height, width, channels)
# and visualize each (height, width) thing in a grid of size approx. sqrt(n) by sqrt(n)
def vis_square(data, padsize=1, padval=0):
    data -= data.min()
    data /= data.max()
    # force the number of filters to be square
    n = int(np.ceil(np.sqrt(data.shape[0])))
    padding = ((0, n ** 2 - data.shape[0]), (0, padsize), (0, padsize)) + ((0, 0),) * (data.ndim - 3)
    data = np.pad(data, padding, mode='constant', constant_values=(padval, padval))
    # tile the filters into an image
    data = data.reshape((n, n) + data.shape[1:]).transpose((0, 2, 1, 3) + tuple(range(4, data.ndim + 1)))
    data = data.reshape((n * data.shape[1], n * data.shape[3]) + data.shape[4:])
    plt.imshow(data)


## ip1
# filters
filters = net.params['ip1'][0].data
filters_normal = np.reshape(filters, (-1, 25, 32))
vis_square(filters_normal)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip1_filters.png')

filters_transposed = filters.transpose()
filters_transposed = np.reshape(filters, (-1, 20, 25))
vis_square(filters_transposed)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip1_filters_transposed.png')

# output
feat = net.blobs['ip1'].data[0]
feat = np.reshape(feat, (-1, 20, 25))  # B*1024 = Bx32x32
vis_square(feat, padval=0.5)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip1_output.png')


## ip2
# filters
filters = net.params['ip2'][0].data  # 10000x1024
filters_normal = np.reshape(filters, (-1, 20, 25))  # 900x00 --> 900x20x20
vis_square(filters_normal)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip2_filters.png')

# filters transposed (should be approximately similar to encode1 filters? not sure if true)
filters_transposed = filters.transpose()
filters_transposed = np.reshape(filters,(-1, 1, 10))
vis_square(filters_transposed)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip2_filters_transposed.png')

# output
feat = net.blobs['ip2'].data[0] #500

plt.clf()
plt.plot(feat.flat)
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip2_output_graph.png')

feat = np.reshape(feat, (-1, 1, 10))  # B*900 --> Bx10x10
vis_square(feat, padval=0.5)
plt.clf()
plt.savefig('visualize/viz_results/mnist_lenet_topology/ip2_output.png')